# Generated by Django 2.0.9 on 2018-11-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('not-speified', 'Not-speified'), ('male', 'Male')], max_length=80, null=True),
        ),
    ]
