# Generated by Django 2.0.9 on 2018-11-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181031_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('not-speified', 'Not-speified'), ('male', 'Male'), ('female', 'Female')], max_length=80, null=True),
        ),
    ]
