# Generated by Django 2.0.9 on 2018-11-19 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181119_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('not-speified', 'Not-speified')], max_length=80, null=True),
        ),
    ]
