# Generated by Django 2.0.9 on 2018-11-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181106_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('not-speified', 'Not-speified'), ('female', 'Female')], max_length=80, null=True),
        ),
    ]
