# Generated by Django 2.0.9 on 2018-11-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20181114_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('not-speified', 'Not-speified'), ('male', 'Male')], max_length=80, null=True),
        ),
    ]
