# Generated by Django 2.0.9 on 2018-11-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20181115_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('not-speified', 'Not-speified')], max_length=80, null=True),
        ),
    ]
