# Generated by Django 2.0.9 on 2018-11-16 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20181115_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('not-speified', 'Not-speified'), ('female', 'Female'), ('male', 'Male')], max_length=80, null=True),
        ),
    ]
